import { Schedule } from "../interface/schedule";
import { Team } from "../interface/team";

export const SEASON_SCHEDULE:Schedule[]=[
    {Id:1,PlayingDate:new Date(2021,08,10),HomeTeam:'AC Milan',AwayTeam:'Inter Milan',
    HomeScore:3,AwayScore:0,
    RefName:'Nicola Rizzoli',Notes:'Overtime'},
    {Id:2,PlayingDate:new Date(2021,08,15),HomeTeam:'Liverpool',AwayTeam:'AC Milan',
    HomeScore:0,AwayScore:3,
    RefName:'Damir Skomina',Notes:'Overtime'},
    {Id:3,PlayingDate:new Date(2021,08,21),HomeTeam:'AC Milan',AwayTeam:'Roma',
    HomeScore:2,AwayScore:1,
    RefName:'Piero Giacomelli',Notes:'Overtime'},
    {Id:4,PlayingDate:new Date(2021,08,29),HomeTeam:'AC Milan',AwayTeam:'Man UTD',
    HomeScore:4,AwayScore:3,
    RefName:'Mark Clattenburg',Notes:'Overtime'},
    {Id:5,PlayingDate:new Date(2021,09,11),HomeTeam:'PSG',AwayTeam:'AC Milan',
    HomeScore:0,AwayScore:2,
    RefName:'Nicola Rizzoli',Notes:'Overtime'},
    {Id:6,PlayingDate:new Date(2021,09,14),HomeTeam:'Fiorentina',AwayTeam:'AC Milan',
    HomeScore:0,AwayScore:1,
    RefName:'Fabrizio Pasqua',Notes:'Overtime'},
    {Id:7,PlayingDate:new Date(2021,09,17),HomeTeam:'Napoli',AwayTeam:'AC Milan',
    HomeScore:1,AwayScore:3,
    RefName:'Daniele Orsato',Notes:'Overtime'},
    {Id:8,PlayingDate:new Date(2021,09,20),HomeTeam:'AC Milan',AwayTeam:'Man City',
    HomeScore:4,AwayScore:0,
    RefName:'Viktor Kassai',Notes:'Overtime'},
    {Id:9,PlayingDate:new Date(2021,09,25),HomeTeam:'AC Milan',AwayTeam:'Juventus',
    HomeScore:1,AwayScore:1,
    RefName:'Michael Fabbri',Notes:'Overtime'},
    {Id:10,PlayingDate:new Date(2021,09,29),HomeTeam:'Real Madrid',AwayTeam:'AC Milan',
    HomeScore:0,AwayScore:1,
    RefName:'Cüneyt Çakır',Notes:'Overtime'},
    {Id:11,PlayingDate:new Date(2021,10,21),HomeTeam:'AC Milan',AwayTeam:'Liverpool',
    HomeScore:3,AwayScore:2,
    RefName:'Manuel Mejuto González',Notes:'Overtime'},
]
export const Teams:Team[]=[
    {Id:1,Name:'AC Milan',Type:'Serie A'},
    {Id:2,Name:'Liverpool',Type:'Premier League'},
    {Id:3,Name:'Inter Milan',Type:'Serie A'},
    {Id:4,Name:'PSG',Type:'Ligue 1'},
    {Id:5,Name:'Man UTD',Type:'Premier League'},
    {Id:6,Name:'Man City',Type:'Premier League'},
    {Id:7,Name:'Juventus',Type:'Serie A'},
    {Id:8,Name:'Napoli',Type:'Serie A'},
    {Id:9,Name:'Bayern',Type:'Bundesliga'},
    {Id:10,Name:'Fiorentina',Type:'Serie A'},
    {Id:11,Name:'Real Madrid',Type:'La Liga'},
]